RetailStore/RetailStore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]

RetailStore/home/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('register', views.register, name='register'),
    path('billing/<slug:contact>', views.billing, name='billing'),
]

RetailStore/home/models.py
from django.db import models

class User(models.Model):
    Name = models.CharField(max_length=100)
    Address = models.CharField(max_length=500)
    Contact = models.CharField(max_length=10)
    Email = models.EmailField(max_length=100)

class Order(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE, related_name='BillingTo')
    Time = models.DateTimeField(auto_now_add=True, editable=False)
    TotalAmount = models.IntegerField()

class Product(models.Model):
    ProductID = models.IntegerField()
    Name = models.CharField(max_length=100)
    Quantity = models.IntegerField()
    Cost = models.IntegerField()
    FinalCost = models.IntegerField()
    orders = models.ManyToManyField(Order)

RetailStore/home/forms.py
from django import forms

class RegisterForm(forms.Form):
    Name = forms.CharField(label='Name', max_length=100)
    Address = forms.CharField(label='Address', max_length=500)
    Contact = forms.CharField(label='Contact', max_length=10)
    Email = forms.EmailField(label='Email', max_length=100)

class BillingStartForm(forms.Form):
    Contact = forms.CharField(label='Contact', max_length=10)

RetailStore/home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import *
from .models import *

def home(request):
    if request.method == 'GET':
        return render(request, 'home/home.html', {
            'message': '',
        })
    elif request.method == 'POST':
        form = BillingStartForm(request.POST)
        if form.is_valid():
            contact = form.cleaned_data['Contact']
            NewUser = User(Contact=contact)
            if NewUser is not None:
                return redirect('billing/'+contact)
            else:
                return render(request, 'home/home.html', {
                    'message': 'User not found. Register if new user.'
                })
        else:
            return render(request, 'home/home.html', {
                'message': 'Fill the contact of the person'
            })

def billing(request, contact):
    if request.method == 'GET':
        return render(request, 'home/billing.html')
    elif request.method == 'POST':
        pass

def register(request):
    if request.method == 'GET':
        form = RegisterForm()
        return render(request, 'home/register.html', {
            'message': '',
        })
    elif request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            NewUser = User()
            NewUser.Name = form.cleaned_data['Name']
            NewUser.Address = form.cleaned_data['Address']
            NewUser.Contact = form.cleaned_data['Contact']
            NewUser.Email = form.cleaned_data['Email']
            NewUser.save()
            return render(request, 'home/register.html', {
                'message': 'User registration successful',
            })
        else:
            return render(request, 'home/register.html', {
                'message': 'User registration unsuccessful'
            })

RetailStore/home/templates/base.html
<html>

    <head>
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body>
        <!-- Menu Bar -->
        <p>Hello world</p>

        <!-- Main Content -->
        {% block content %}
        {% endblock %}
    </body>

</html>

RetailStore/home/templates/home/billing.html
{% extends 'base.html' %}

{% block title %}Kirana Retail Store: Billing{% endblock %}

{% block content %}

Yo

{% endblock %}

RetailStore/home/templates/home/home.html
{% extends "base.html" %}

{% block title %}Kirana Retail Store: Home{% endblock %}

{% block content %}

<form name="EnterUser" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="Contact" placeholder="Enter contact of the person"></input>
    <input type="submit" value="Start billing"></input>
</form>

<a href="{% url 'home:register' %}">Register a person</a>

{% endblock %}

RetailStore/home/templates/home/register.html
{% extends 'base.html' %}

{% block title %}Kirana Retail Store: Registration{% endblock %}

{% block content %}

<form name="RegisterUser" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="Name" placeholder="Enter name of the person"></input>
    <input type="text" name="Address" placeholder="Enter home address"></input>
    <input type="text" name="Contact" placeholder="Enter contact of the person"></input>
    <input type="email" name="Email" placeholder="Enter email of the person"></input>
    <input type="submit" value="Register"></input>
</form>

{% endblock %}